// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StocksApi.Providers.Sqlite;

#nullable disable

namespace StocksApi.Providers.Sqlite.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    partial class SqliteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StockNewsStockTrend", b =>
                {
                    b.Property<int>("StockNewsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockTrendId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockNewsId", "StockTrendId");

                    b.HasIndex("StockTrendId");

                    b.ToTable("StockNewsStockTrend");
                });

            modelBuilder.Entity("StocksAbstractions.Models.MarketTrend", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrendName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrendName")
                        .IsUnique();

                    b.ToTable("MarketTrends");
                });

            modelBuilder.Entity("StocksAbstractions.Models.MarketTrends.StockNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticlePhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketTrendId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketTrendId");

                    b.ToTable("StockNews");
                });

            modelBuilder.Entity("StocksAbstractions.Models.MarketTrends.StockTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Change")
                        .HasColumnType("REAL");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("REAL");

                    b.Property<string>("CountryCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exchange")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeClose")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeOpen")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketTrendId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PreOrPostMarket")
                        .HasColumnType("REAL");

                    b.Property<double?>("PreOrPostMarketChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("PreOrPostMarketChangePercent")
                        .HasColumnType("REAL");

                    b.Property<double?>("PreviousClose")
                        .HasColumnType("REAL");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarketTrendId");

                    b.ToTable("StockTrends");
                });

            modelBuilder.Entity("StocksAbstractions.Models.SearchResult", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchTerm")
                        .IsUnique();

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("StocksAbstractions.Models.SearchResults.StockSearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExchDisp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchResultId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeDisp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SearchResultId");

                    b.ToTable("StockSearchResults");
                });

            modelBuilder.Entity("StocksAbstractions.Models.Stock", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalystRating")
                        .HasColumnType("TEXT");

                    b.Property<double>("EpsCurrentYear")
                        .HasColumnType("REAL");

                    b.Property<double>("EpsForward")
                        .HasColumnType("REAL");

                    b.Property<double>("FiftyDayAverage")
                        .HasColumnType("REAL");

                    b.Property<double>("FiftyTwoWeekHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("FiftyTwoWeekLow")
                        .HasColumnType("REAL");

                    b.Property<string>("FiftyTwoWeekRange")
                        .HasColumnType("TEXT");

                    b.Property<double>("ForwardPE")
                        .HasColumnType("REAL");

                    b.Property<string>("FullExchangeName")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LastHistoryUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("RegularMarketChange")
                        .HasColumnType("REAL");

                    b.Property<double>("RegularMarketChangePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("RegularMarketDayHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("RegularMarketDayLow")
                        .HasColumnType("REAL");

                    b.Property<string>("RegularMarketDayRange")
                        .HasColumnType("TEXT");

                    b.Property<double>("RegularMarketOpen")
                        .HasColumnType("REAL");

                    b.Property<double>("RegularMarketPreviousClose")
                        .HasColumnType("REAL");

                    b.Property<long>("RegularMarketVolume")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetPriceHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetPriceLow")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetPriceMean")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetPriceMedian")
                        .HasColumnType("REAL");

                    b.Property<double>("TwoHundredDayAverage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("StocksAbstractions.Models.Stocks.StockHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("DayHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("DayLow")
                        .HasColumnType("REAL");

                    b.Property<string>("DayRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DayVolume")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PriceClose")
                        .HasColumnType("REAL");

                    b.Property<double>("PriceOpen")
                        .HasColumnType("REAL");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockSymbol");

                    b.HasIndex("StockSymbol", "Date");

                    b.ToTable("StockHistory");
                });

            modelBuilder.Entity("UsersAbstractions.Models.Notifications.StockNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTargetBiggerThanOrEqual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShouldBeNotified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("StockNotification");
                });

            modelBuilder.Entity("StockNewsStockTrend", b =>
                {
                    b.HasOne("StocksAbstractions.Models.MarketTrends.StockNews", null)
                        .WithMany()
                        .HasForeignKey("StockNewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StocksAbstractions.Models.MarketTrends.StockTrend", null)
                        .WithMany()
                        .HasForeignKey("StockTrendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StocksAbstractions.Models.MarketTrends.StockNews", b =>
                {
                    b.HasOne("StocksAbstractions.Models.MarketTrend", null)
                        .WithMany("StockNews")
                        .HasForeignKey("MarketTrendId");
                });

            modelBuilder.Entity("StocksAbstractions.Models.MarketTrends.StockTrend", b =>
                {
                    b.HasOne("StocksAbstractions.Models.MarketTrend", null)
                        .WithMany("TrendingStocks")
                        .HasForeignKey("MarketTrendId");
                });

            modelBuilder.Entity("StocksAbstractions.Models.SearchResults.StockSearchResult", b =>
                {
                    b.HasOne("StocksAbstractions.Models.SearchResult", null)
                        .WithMany("StockSearchResults")
                        .HasForeignKey("SearchResultId");
                });

            modelBuilder.Entity("StocksAbstractions.Models.Stock", b =>
                {
                    b.OwnsOne("StocksAbstractions.Models.Stocks.StockAnalysis", "Analysis", b1 =>
                        {
                            b1.Property<string>("StockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("AnalysisSymbol");

                            b1.Property<double>("TargetHighPrice")
                                .HasColumnType("REAL")
                                .HasColumnName("AnalysisTargetHighPrice");

                            b1.Property<double>("TargetLowPrice")
                                .HasColumnType("REAL")
                                .HasColumnName("AnalysisTargetLowPrice");

                            b1.Property<double>("TargetMeanPrice")
                                .HasColumnType("REAL")
                                .HasColumnName("AnalysisTargetMeanPrice");

                            b1.Property<double>("TargetMedianPrice")
                                .HasColumnType("REAL")
                                .HasColumnName("AnalysisTargetMedianPrice");

                            b1.Property<DateTime>("UpdatedTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("AnalysisUpdatedTime");

                            b1.HasKey("StockId");

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("UsersAbstractions.Models.Notifications.StockNotification", b =>
                {
                    b.HasOne("StocksAbstractions.Models.Stock", null)
                        .WithMany("StockNotifications")
                        .HasForeignKey("StockId");
                });

            modelBuilder.Entity("StocksAbstractions.Models.MarketTrend", b =>
                {
                    b.Navigation("StockNews");

                    b.Navigation("TrendingStocks");
                });

            modelBuilder.Entity("StocksAbstractions.Models.SearchResult", b =>
                {
                    b.Navigation("StockSearchResults");
                });

            modelBuilder.Entity("StocksAbstractions.Models.Stock", b =>
                {
                    b.Navigation("StockNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
