version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/FinanceGrid.WebClient"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "nuget"
    directory: "/FinanceGrid"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    groups:
      nuget-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/FinanceGrid/FinanceGrid.Gateway"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/FinanceGrid/FinancialData/FinanceGrid.FinancialData.Api"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/FinanceGrid/Users/FinanceGrid.Users.Api"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/FinanceGrid/Webhook/FinanceGrid.Webhook.Api"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/FinanceGrid/Webhook/FinanceGrid.Webhook.Processing"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/FinanceGrid.WebClient"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
