networks:
  network-stocks:
    driver: bridge

services:
  frontend:
    container_name: stocks-collection
    environment:
      - ANGULAR_BUILD_CONFIGURATION=development
    ports:
      - "4200:80"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    depends_on:
      - gateway
    build:
      context: ./client-angular
      dockerfile: Dockerfile
    networks:
      - network-stocks

  gateway:
    container_name: gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    depends_on:
      - stocks-service
      - users-service
    build:
      context: ./StocksApi
      dockerfile: ./Gateway/Dockerfile
    networks:
      - network-stocks

  stocks-service:
    container_name: stocks-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    build:
      context: ./StocksApi
      dockerfile: ./StocksService/Dockerfile
    networks:
      - network-stocks

  users-service:
    container_name: users-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"
    build:
      context: ./StocksApi
      dockerfile: ./UsersService/Dockerfile
    networks:
      - network-stocks

  backend:
    container_name: stocksapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5108
      - SECRETS_FILE_PATH=/etc/secrets/secrets.json
    ports:
      - "5108:5108"
    volumes:
      - ./StocksApi/StocksApi/secrets.json:/etc/secrets/secrets.json
    build:
      context: ./StocksApi
      dockerfile: ./StocksApi/Dockerfile
    networks:
      - network-stocks

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - network-stocks
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
