// <auto-generated />
using System;
using FinanceGrid.FinancialData.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceGrid.FinancialData.Infrastructure.Migrations
{
    [DbContext(typeof(FinancialDataDbContext))]
    partial class FinancialDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.MarketTrend", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrendName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TrendName")
                        .IsUnique();

                    b.ToTable("MarketTrends");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.SearchResult", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchTerm")
                        .IsUnique();

                    b.ToTable("SearchResults");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.Stock", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AnalystRating")
                        .HasColumnType("text");

                    b.Property<double>("EpsCurrentYear")
                        .HasColumnType("double precision");

                    b.Property<double>("EpsForward")
                        .HasColumnType("double precision");

                    b.Property<double>("FiftyDayAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("FiftyTwoWeekHigh")
                        .HasColumnType("double precision");

                    b.Property<double>("FiftyTwoWeekLow")
                        .HasColumnType("double precision");

                    b.Property<string>("FiftyTwoWeekRange")
                        .HasColumnType("text");

                    b.Property<double>("ForwardPE")
                        .HasColumnType("double precision");

                    b.Property<string>("FullExchangeName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("LastHistoryUpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularMarketChange")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularMarketChangePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularMarketDayHigh")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularMarketDayLow")
                        .HasColumnType("double precision");

                    b.Property<string>("RegularMarketDayRange")
                        .HasColumnType("text");

                    b.Property<double>("RegularMarketOpen")
                        .HasColumnType("double precision");

                    b.Property<double>("RegularMarketPreviousClose")
                        .HasColumnType("double precision");

                    b.Property<long>("RegularMarketVolume")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TargetPriceHigh")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetPriceLow")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetPriceMean")
                        .HasColumnType("double precision");

                    b.Property<double>("TargetPriceMedian")
                        .HasColumnType("double precision");

                    b.Property<double>("TwoHundredDayAverage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockHistoryEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("DayHigh")
                        .HasColumnType("double precision");

                    b.Property<double>("DayLow")
                        .HasColumnType("double precision");

                    b.Property<string>("DayRange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DayVolume")
                        .HasColumnType("bigint");

                    b.Property<double>("PriceClose")
                        .HasColumnType("double precision");

                    b.Property<double>("PriceOpen")
                        .HasColumnType("double precision");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StockSymbol");

                    b.HasIndex("StockSymbol", "Date");

                    b.ToTable("StockHistory");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticlePhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("ArticleTitle")
                        .HasColumnType("text");

                    b.Property<string>("ArticleUrl")
                        .HasColumnType("text");

                    b.Property<string>("MarketTrendId")
                        .HasColumnType("text");

                    b.Property<string>("PostTimeUtc")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarketTrendId");

                    b.ToTable("StockNews");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockSearchResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExchDisp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchResultId")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDisp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchResultId");

                    b.ToTable("StockSearchResults");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockTrend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Change")
                        .HasColumnType("double precision");

                    b.Property<double?>("ChangePercent")
                        .HasColumnType("double precision");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .HasColumnType("text");

                    b.Property<string>("ExchangeClose")
                        .HasColumnType("text");

                    b.Property<string>("ExchangeOpen")
                        .HasColumnType("text");

                    b.Property<string>("LastUpdateUtc")
                        .HasColumnType("text");

                    b.Property<string>("MarketTrendId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double?>("PreOrPostMarket")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreOrPostMarketChange")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreOrPostMarketChangePercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("PreviousClose")
                        .HasColumnType("double precision");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarketTrendId");

                    b.ToTable("StockTrends");
                });

            modelBuilder.Entity("StockNewsStockTrend", b =>
                {
                    b.Property<int>("StockNewsId")
                        .HasColumnType("integer");

                    b.Property<int>("StockTrendId")
                        .HasColumnType("integer");

                    b.HasKey("StockNewsId", "StockTrendId");

                    b.HasIndex("StockTrendId");

                    b.ToTable("StockNewsStockTrend");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.Stock", b =>
                {
                    b.OwnsOne("FinanceGrid.FinancialData.Domain.Entities.StockAnalysis", "Analysis", b1 =>
                        {
                            b1.Property<string>("StockId")
                                .HasColumnType("text");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("AnalysisSymbol");

                            b1.Property<double>("TargetHighPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("AnalysisTargetHighPrice");

                            b1.Property<double>("TargetLowPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("AnalysisTargetLowPrice");

                            b1.Property<double>("TargetMeanPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("AnalysisTargetMeanPrice");

                            b1.Property<double>("TargetMedianPrice")
                                .HasColumnType("double precision")
                                .HasColumnName("AnalysisTargetMedianPrice");

                            b1.Property<DateTime>("UpdatedTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("AnalysisUpdatedTime");

                            b1.HasKey("StockId");

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockNews", b =>
                {
                    b.HasOne("FinanceGrid.FinancialData.Domain.Entities.MarketTrend", null)
                        .WithMany("StockNewsItems")
                        .HasForeignKey("MarketTrendId");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockSearchResult", b =>
                {
                    b.HasOne("FinanceGrid.FinancialData.Domain.Entities.SearchResult", null)
                        .WithMany("StockSearchResults")
                        .HasForeignKey("SearchResultId");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.StockTrend", b =>
                {
                    b.HasOne("FinanceGrid.FinancialData.Domain.Entities.MarketTrend", null)
                        .WithMany("TrendingStocks")
                        .HasForeignKey("MarketTrendId");
                });

            modelBuilder.Entity("StockNewsStockTrend", b =>
                {
                    b.HasOne("FinanceGrid.FinancialData.Domain.Entities.StockNews", null)
                        .WithMany()
                        .HasForeignKey("StockNewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceGrid.FinancialData.Domain.Entities.StockTrend", null)
                        .WithMany()
                        .HasForeignKey("StockTrendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.MarketTrend", b =>
                {
                    b.Navigation("StockNewsItems");

                    b.Navigation("TrendingStocks");
                });

            modelBuilder.Entity("FinanceGrid.FinancialData.Domain.Entities.SearchResult", b =>
                {
                    b.Navigation("StockSearchResults");
                });
#pragma warning restore 612, 618
        }
    }
}
