// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StocksApi.Providers.UsersSqlite;

#nullable disable

namespace StocksApi.Providers.UsersSqlite.Migrations
{
    [DbContext(typeof(UsersSqliteDbContext))]
    [Migration("20260530133501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("StocksApi.Providers.UsersSqlite.WatchListName", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail", "Name")
                        .IsUnique();

                    b.ToTable("WatchListNames");
                });

            modelBuilder.Entity("UsersAbstractions.Models.Notifications.StockNotification", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTargetBiggerThanOrEqual")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShouldBeNotified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.ToTable("StockNotifications");
                });

            modelBuilder.Entity("UsersAbstractions.Models.Shares.Share", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseGuid")
                        .HasColumnType("TEXT");

                    b.Property<double>("PurchasingPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("UserStockWatchId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseGuid")
                        .IsUnique();

                    b.HasIndex("UserStockWatchId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("UsersAbstractions.Models.Shares.UserStockWatch", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail");

                    b.HasIndex("UserEmail", "ListName");

                    b.ToTable("UserStockWatches");
                });

            modelBuilder.Entity("UsersAbstractions.Models.StockNotes.UserStockNote", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StockSymbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail", "StockSymbol");

                    b.ToTable("UserStockNotes");
                });

            modelBuilder.Entity("UsersAbstractions.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StocksApi.Providers.UsersSqlite.WatchListName", b =>
                {
                    b.HasOne("UsersAbstractions.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsersAbstractions.Models.Notifications.StockNotification", b =>
                {
                    b.HasOne("UsersAbstractions.Models.User", null)
                        .WithMany("StockNotifications")
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsersAbstractions.Models.Shares.Share", b =>
                {
                    b.HasOne("UsersAbstractions.Models.Shares.UserStockWatch", null)
                        .WithMany()
                        .HasForeignKey("UserStockWatchId");
                });

            modelBuilder.Entity("UsersAbstractions.Models.Shares.UserStockWatch", b =>
                {
                    b.HasOne("UsersAbstractions.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UsersAbstractions.Models.StockNotes.UserStockNote", b =>
                {
                    b.HasOne("UsersAbstractions.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email");
                });

            modelBuilder.Entity("UsersAbstractions.Models.User", b =>
                {
                    b.Navigation("StockNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
