@startuml
start

:משתמש בוחר תיק לניהול;
:משתמש בוחר את הפעולה הדרושה;

if (איזה פעולה המשתמש רוצה לבצע?) then (הוספת מניה חדשה)
    :לחיצה על כפתור הוספה;
    :הזנת סימול המניה;
    :שליחת בקשה להוספה לתיק לשרת;
    if (האם הבקשה הושלמה בהצלחה?) then (כן)
        :הוספה של מניה לתיק;
        :התראה על הצלחה;
        :הוספת מניה לתיק ברשימה;
    else (לא)
        :התראה על שגיאה במסך;
    endif
else if (עדכון מניה קיימת) then (עדכון מניה קיימת)
    :עדכון מניה בתיק;
else if (מחיקת מניה) then (מחיקת מניה)
    :לחיצה על כפתור מחיקה בשורת המניה;
    :שליחת בקשה לשרת למחיקת המניה מהתיק;
    if (האם הבקשה התבצעה בהצלחה?) then (כן)
        :מחיקת המניה מהתיק;
        :הצגת התראת הצלחה;
        :עדכון התיק במסך;
    else (לא)
        :הצגת התראת שגיאה;
    endif
endif

stop
@enduml
