@startuml

start
:עדכון מניה בתיק;

if (מה לעדכן?) then (פתק)
    :לחיצה על כפתור עדכון הפתק;
    :הזנת הפתק החדש;
    :לחיצה על עדכון;
    :שליחת בקשה לשרת לעדכון פתק;
    if (האם הבקשה בוצעה בהצלחה?) then (כן)
        :עדכון פתק המניה;
        :הצגת התראת הצלחה;
    else (לא)
        :הצגת התראת שגיאה;
    endif
else (חלקי מניה)
    :לחיצה על כפתור עדכון חלקי מניה;
    :מעבר למסך עדכון חלקי מניה;
    if (הוספה או מחיקת מניות?) then (מחיקת מניות)
        :לחיצה על כפתור מחיקה של המניות;
        :שליחת בקשה למחיקת המניות;
        if (האם הבקשה בוצעה בהצלחה?) then (כן)
            :מחיקת חלקי המניה;
            :הצגת התראת הצלחה;
            :עדכון חלקי המניה במסך;
        else (לא)
            :הצגת התראת שגיאה;
        endif
    else (הוספת חלקי מניה)
        :לחיצה על כפתור הוספת חלקי מניה;
        :הזנת פרטים להוספה של רכישת מניות;
        :שליחת בקשה להוספת חלקי מניה;
        if (האם הבקשה בוצעה בהצלחה?) then (כן)
            :הוספת חלקי המניה;
            :הצגת התראת הצלחה;
            :עדכון חלקי המניה במסך;
        else (לא)
            :הצגת התראת שגיאה;
        endif
    endif
endif

stop
@enduml