@startuml
start

:הצגת ערכי המניה על המסך;

switch (משתמש בוחר פעולה לבצע)
case ( צפייה בערכי מניה וניתוח ערכי מניה )
    :מש;
case ( הוספת מניה לתיק ) 
    :Text 2;
case ( הוספת התראה לערך מניה )
    :Text 3;
    if(האם המשתמש מחובר?) then (כן)
        :משתמש בוחר את ערך המניה הרצוי;
        :משתמש לוחץ על כפתור ההוספה;
    else(לא)
        :המשתמש מופנה למסך ההתחברות;
endif
endswitch

stop
@enduml