@startuml
start

:מעבר לעמוד חיפוש מניות;
:הזנת ערך חיפוש;

:שליחה של ערך החיפוש לשרת;
:קבלת מניות לפי ערך החיפוש מהשרת;

:הצגת המניות בדף;
:משתמש בוחר מניה;

if (האם ערך המניה קיים בשרת?) then (כן)
    :שליחת ערך המניה למשתמש;
    :הצגת ערך המניה על המסך;
else (לא)
    :נשלחת בקשה לקבלת ערך המניה בשוק ההון;
    if (האם המניה נמצאה?) then (כן)
        :הוספת ערך המניה לשרת;
        :שליחת ערך המניה למשתמש;
        :הצגת ערך המניה על המסך;
    else (לא)
        :הצגת הודעת שגיאה;
    endif
endif

stop
@enduml