@startuml
start

:דף ההתחברות;

if (האם המשתמש רשום?) then (כן)
    :ניסיון התחברות;
    if (האם המשתמש זוכר את הסיסמה שלו?) then (כן)
        :מזין פרטי משתמש ולוחץ על התחברות;
        if (האם פרטי ההתחברות נכונים?) then (כן)
            :התחברות תקינה;
        else (לא)
            :הצגת הערת התחברות;
        endif
    else (לא)
        :משתמש לוחץ על עדכון סיסמה;
        :משתמש מזין מייל וסיסמה חדשה;
        if (האם האימייל נכון?) then (כן)
            :סיסמא מעודכנת בשרת;
            :חזרה לעמוד ההתחברות;
        else (לא)
            :הצגת הודעת שגיאה;
        endif
    endif
else (לא)
    :לחיצה על כפתור ההרשמה;
    :מילוי פרטים אישיים וסיסמה;
    if (האם פרטי המשתמש תקינים?) then (כן)
        :רישום משתמש;
        :חזרה לעמוד ההתחברות;
    else (לא)
        :הצגת הודעת שגיאה;
    endif
endif

stop
@enduml