namespace YahooFinance.Models.Price
{
    public class PriceResponse
    {
        public string? Language { get; set; }
        public string? Region { get; set; }
        public string? QuoteType { get; set; }
        public string? TypeDisp { get; set; }
        public string? QuoteSourceName { get; set; }
        public QuoteSummary? QuoteSummary { get; set; }
        public string? Currency { get; set; }
        public long EarningsTimestamp { get; set; }
        public long EarningsTimestampStart { get; set; }
        public long EarningsTimestampEnd { get; set; }
        public double TrailingAnnualDividendRate { get; set; }
        public double TrailingPE { get; set; }
        public double DividendsPerShare { get; set; }
        public double DividendRate { get; set; }
        public double TrailingAnnualDividendYield { get; set; }
        public double DividendYield { get; set; }
        public double Revenue { get; set; }
        public double PriceToSales { get; set; }
        public double EpsTrailingTwelveMonths { get; set; }
        public double EpsForward { get; set; }
        public double EpsCurrentYear { get; set; }
        public double EpsNextQuarter { get; set; }
        public double PriceEpsCurrentYear { get; set; }
        public double PriceEpsNextQuarter { get; set; }
        public double BookValue { get; set; }
        public double FiftyDayAverage { get; set; }
        public double FiftyDayAverageChange { get; set; }
        public double FiftyDayAverageChangePercent { get; set; }
        public double TwoHundredDayAverage { get; set; }
        public double TwoHundredDayAverageChange { get; set; }
        public double TwoHundredDayAverageChangePercent { get; set; }
        public long MarketCap { get; set; }
        public double ForwardPE { get; set; }
        public double PriceToBook { get; set; }
        public string? ExchangeTimezoneName { get; set; }
        public string? ExchangeTimezoneShortName { get; set; }
        public long FirstTradeDateMilliseconds { get; set; }
        public int PriceHint { get; set; }
        public double TotalCash { get; set; }
        public long FloatShares { get; set; }
        public double Ebitda { get; set; }
        public double ShortRatio { get; set; }
        public double PreMarketChange { get; set; }
        public double PreMarketChangePercent { get; set; }
        public long PreMarketTime { get; set; }
        public double TargetPriceHigh { get; set; }
        public double TargetPriceLow { get; set; }
        public double TargetPriceMean { get; set; }
        public double TargetPriceMedian { get; set; }
        public double PreMarketPrice { get; set; }
        public double HeldPercentInsiders { get; set; }
        public double HeldPercentInstitutions { get; set; }
        public double RegularMarketChange { get; set; }
        public double RegularMarketChangePercent { get; set; }
        public long RegularMarketTime { get; set; }
        public double RegularMarketPrice { get; set; }
        public double RegularMarketDayHigh { get; set; }
        public string? RegularMarketDayRange { get; set; }
        public double RegularMarketDayLow { get; set; }
        public long RegularMarketVolume { get; set; }
        public long SharesShort { get; set; }
        public long SharesShortPrevMonth { get; set; }
        public double ShortPercentFloat { get; set; }
        public double RegularMarketPreviousClose { get; set; }
        public double Bid { get; set; }
        public double Ask { get; set; }
        public string? Exchange { get; set; }
        public string? Market { get; set; }
        public string? FullExchangeName { get; set; }
        public string? ShortName { get; set; }
        public string? LongName { get; set; }
        public string? FinancialCurrency { get; set; }
        public double RegularMarketOpen { get; set; }
        public long AverageDailyVolume3Month { get; set; }
        public long AverageDailyVolume10Day { get; set; }
        public double FiftyTwoWeekLowChange { get; set; }
        public double FiftyTwoWeekLowChangePercent { get; set; }
        public string? FiftyTwoWeekRange { get; set; }
        public double FiftyTwoWeekHighChange { get; set; }
        public double FiftyTwoWeekHighChangePercent { get; set; }
        public double FiftyTwoWeekLow { get; set; }
        public double FiftyTwoWeekHigh { get; set; }
        public long DividendDate { get; set; }
        public long ExDividendDate { get; set; }
        public string? Symbol { get; set; }
        public string? AverageAnalystRating { get; set; }
    }
}